string prompt                                   # prompt
bool reset                                      # whether to reset the context
llama_msgs/SamplingConfig sampling_config       # sampling config
---
llama_msgs/Response response                    # final response
---
llama_msgs/PartialResponse partial_response     # partial response
